### ISSUE TITLE
The implementation of the whole project

### ISSUE THREAD

**Issue by Avimitin** [Avimitin/dfm#1]
This issue discuss and try different implementation of the dfm project.

## Target

It's more than a dotfile manager. I want it to be a tiny simple build system.

1. A file to provide information, and it should be easy to read and easy to maintain.
2. The information file should contains user-side hook, like `post-install`, to have customized setup.
3. Cli program should be robust, reusable, maintainable. And there is no speed requirement, I just need a friendly and high level language.

### Backend

- [ ] ~~Deno + typescript?~~: To many dependency and compatibility issues to resolve. Also bad for cross multiplatform.
- [ ] Rust?
- [ ] [~~Bash~~](https://github.com/Avimitin/dfm/issues/1#issuecomment-1304737857): To hard to implement, to hard to maintain and find bug.

### Information File

- [ ] Bash?
- [ ] ~~Lua?~~: bad syntax, lot's of difference between versions.
- [ ] ~~JavaScript?~~: It is not a good IDEA to bring the whole V8 engine into a dotfile manager
- [ ] [~~KDL?~~](https://github.com/Avimitin/dfm/issues/1#issuecomment-1304739487)

**Comment by Avimitin** [comment]
## The name of the information file

## Prefix DOT to hidden it?

- [ ] Y
- [ ] N

## The name?

- [ ] `.build`, `DOTBUILD`
- [ ] `.install`, `DOTINSTALL`
- [ ] `.dfm`, `DFM`

**Comment by Avimitin** [comment]
# The implementation (**Abandoned**)

BASH is so hard to write. Although the PKGBUILD like information file is really great and easy to use, but the cli is so hard to write and not easy to maintain.

## Pure BASH

Implement the `dfm` executable in pure BASH script like the Arch Linux `makepkg`. And all the `.dfm` file just yet another PKGBUILD.

## Benefit

- All the benefit from PKGBUILD
- Single curl command to get the cli works from all machines that have bash.

## Disadvantage

- Bash is hard to write and error-prone.

## Actual Example

- the build specification file

```bash
name="nvim"
descriptions="An example file showing how to manage the neovim configuration"
depends_arch_linux=('nvim-git' 'ripgrep' 'fzf' 'fd' 'git-delta')
url="https://github.com/Avimitin/nvim"

# dotfile/
#   * nvim/
#       * DOTBUILD
#       * config/     <- whatever name you like
#           * init.lua
#           *  ...
#   * .dfm

prepare() {
  echo "Pull the submodule"
  git submodule update --init
}

install() {
  ln -sf "${srcdir}/config" "${HOME}/.config/nvim"
}

post-install() {
  echo "Downloading plugins"
  nvim --headless -c "au User PackerComplete quitall"
}
```

## The cli

```bash
# fake code
for d in ${dirs[@]}; do
  source ${d}/DOTBUILD
  download_depends $depends[*]
  prepare
  install
  post-install

  unset prepare install post-install name descriptions url depends
done
```

**Comment by Avimitin** [comment]
# The Implementation

## Rust CLI, a documentation language to provide information

kdl: https://kdl.dev/

## Benefit

- Writing KDL is like writing the bash script

## Disadvantage

- KDL is a developing project, it is not stable yet
- There is no array in KDL. Node can have multiple value but a `node` is terminated by new line, so we need `\` to spread multiple line.
- Single quote quoted line is not considered as string, this might lead to problematic escape sequences.

## Actual example

<details>
<summary>KDL</summary>

```rust
use kdl::KdlDocument;

fn main() -> miette::Result<()> {
    let kdl_raw = r#"
name "nvim"
depends {
    arch_linux "git" "neovim-git" "ripgrep"
    alpine "git" "neovim" "ripgrep" "alpine-sdk"
}
source \
    "./nvim-source" \
    "mypatch::https://example.com/some-extra-patch" \
    "git+https://github.com/somebody/extra.git"

prepare {
    log "Log is built-in field that can help you print something to terminal"
}

install {
    // setup some temporary variable
    env "NVIM_CFG_DIR" "~/.config/nvim"

    // ln is also built-in field that do the soft link works.
    // Relative path is acceptable
    ln src="./nvim-source" dest="$NVIM_CFG_DIR"

    // exec is a built-in action that execute the command in bash
    //
    // $srcdir is a internal variable that point to the directory
    // where .build.kdl locate.
    exec "patch -p0 -Ni ${srcdir}/mypatch"

    // this is also built-in
    cp "extra" "~/.config/nvim/extra"

    cp "$NVIM_CFG_DIR/custom.example.lua" "$NVIM_CFG_DIR/custom.lua"
}

post-install {
    exec "nvim --headless -c 'autocmd User PackerComplete quitall'"
}
    "#;

    let parsed: KdlDocument = kdl_raw.parse()?;
    dbg!(parsed);
    Ok(())
}
```

</details>

<details>
<summary>JSON</summary>

```json
{
  "name": "nvim",
  "depends": {
    "arch_linux": ["neovim-git", "ripgrep", "git"],
    "alpine": ["neovim-git", "ripgrep", "alpine-sdk", "git"]
  },
  "source": [
    "./*",
    "SomePatch::https://github.com/SomeBody/SomePlugin/pull/114514.diff",
    "extra::git+https://github.com/SomeBody/ExtraPlugin.git"
  ],

  "steps": [
    {
      "name": "prepare",
      "extra-key": "reusable-value",
      "packer_dir":  "~/.local/share/nvim/site/pack/packer/opt/",
      "seqs": [
        {"mkdir": ["~/.config", "$packer_dir", "~/.cache"]},
        {"copy": ["./extra", "$packer_dir"]}
      ]
    },
    {
      "name": "install",
      "nvim_cfg_dir": "~/.config/nvim",
      "seqs": [
        { "symlink": ["$srcdir", "nvim_cfg_dir"] },
        { "execute": ["cd ~/.config/nvim", "patch -p0 -Ni ${src_dir}/SomePatch" ] },
        { "cp": ["${nvim_cfg_dir}/custom.example.lua", "${nvim_cfg_dir}/custom.lua"]}
      ]
    },
    {
      "name": "post-install",
      "seqs": [
        {"exec": ["nvim --headless -c 'autocmd User PackerComplete quitall'"]}
      ]
    }
  ]
}

```

</details>

<details>
<summary>YAML</summary>

```yaml
---
name: nvim
depends:
  arch_linux:
  - neovim-git
  - ripgrep
  - git
  alpine:
  - neovim-git
  - ripgrep
  - alpine-sdk
  - git
source:
- "./*"
- SomePatch::https://github.com/SomeBody/SomePlugin/pull/114514.diff
- extra::git+https://github.com/SomeBody/ExtraPlugin.git
steps:
- name: prepare
  extra-key: reusable-value
  packer_dir: "~/.local/share/nvim/site/pack/packer/opt/"
  seqs:
  - mkdir:
    - "~/.config"
    - "$packer_dir"
    - "~/.cache"
  - copy:
    - "./extra"
    - "$packer_dir"
- name: install
  nvim_cfg_dir: "~/.config/nvim"
  seqs:
  - symlink:
    - "$srcdir"
    - nvim_cfg_dir
  - execute:
    - cd ~/.config/nvim
    - patch -p0 -Ni ${src_dir}/SomePatch
  - cp:
    - "${nvim_cfg_dir}/custom.example.lua"
    - "${nvim_cfg_dir}/custom.lua"
- name: post-install
  seqs:
  - exec:
    - nvim --headless -c 'autocmd User PackerComplete quitall'

```


</details>

<details>
<summary>toml</summary>

```toml
name = "nvim"
source = [
  "./*",
  "SomePatch::https://github.com/SomeBody/SomePlugin/pull/114514.diff",
  "extra::git+https://github.com/SomeBody/ExtraPlugin.git"
]

[depends]
arch_linux = [ "neovim-git", "ripgrep", "git" ]
alpine = [ "neovim-git", "ripgrep", "alpine-sdk", "git" ]

[[steps]]
name = "prepare"
extra-key = "reusable-value"
packer_dir = "~/.local/share/nvim/site/pack/packer/opt/"

  [[steps.seqs]]
  mkdir = [ "~/.config", "$packer_dir", "~/.cache" ]

  [[steps.seqs]]
  copy = [ "./extra", "$packer_dir" ]

[[steps]]
name = "install"
nvim_cfg_dir = "~/.config/nvim"

  [[steps.seqs]]
  symlink = [ "$srcdir", "nvim_cfg_dir" ]

  [[steps.seqs]]
  execute = [ "cd ~/.config/nvim", "patch -p0 -Ni ${src_dir}/SomePatch" ]

  [[steps.seqs]]
  cp = [
  "${nvim_cfg_dir}/custom.example.lua",
  "${nvim_cfg_dir}/custom.lua"
]

[[steps]]
name = "post-install"

  [[steps.seqs]]
  exec = [ "nvim --headless -c 'autocmd User PackerComplete quitall'" ]

```

</details>
